--
-- PostgreSQL database dump
--

\restrict EZ8A9GBZT6YqkMq5Hc9LCk88UVwcLZqEmAaaNTDv71o6l4iN787ebH0P8ZcSpgZ

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.students DROP CONSTRAINT IF EXISTS students_id_tutor_fkey;
ALTER TABLE IF EXISTS ONLY public.sessions DROP CONSTRAINT IF EXISTS sessions_id_student_fkey;
ALTER TABLE IF EXISTS ONLY public.level_results DROP CONSTRAINT IF EXISTS level_results_id_session_fkey;
ALTER TABLE IF EXISTS ONLY public.level_results DROP CONSTRAINT IF EXISTS level_results_id_level_fkey;
DROP INDEX IF EXISTS public.admins_username_key;
DROP INDEX IF EXISTS public.admins_email_key;
ALTER TABLE IF EXISTS ONLY public.tutors DROP CONSTRAINT IF EXISTS tutors_pkey;
ALTER TABLE IF EXISTS ONLY public.tutors DROP CONSTRAINT IF EXISTS tutors_email_key;
ALTER TABLE IF EXISTS ONLY public.students DROP CONSTRAINT IF EXISTS students_pkey;
ALTER TABLE IF EXISTS ONLY public.sessions DROP CONSTRAINT IF EXISTS sessions_pkey;
ALTER TABLE IF EXISTS ONLY public.levels DROP CONSTRAINT IF EXISTS levels_pkey;
ALTER TABLE IF EXISTS ONLY public.level_results DROP CONSTRAINT IF EXISTS level_results_pkey;
ALTER TABLE IF EXISTS ONLY public.admins DROP CONSTRAINT IF EXISTS admins_pkey;
ALTER TABLE IF EXISTS public.tutors ALTER COLUMN id_tutor DROP DEFAULT;
ALTER TABLE IF EXISTS public.students ALTER COLUMN id_student DROP DEFAULT;
ALTER TABLE IF EXISTS public.sessions ALTER COLUMN id_session DROP DEFAULT;
ALTER TABLE IF EXISTS public.levels ALTER COLUMN id_level DROP DEFAULT;
ALTER TABLE IF EXISTS public.level_results ALTER COLUMN id_result DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.tutors_id_tutor_seq;
DROP TABLE IF EXISTS public.tutors;
DROP SEQUENCE IF EXISTS public.students_id_student_seq;
DROP TABLE IF EXISTS public.students;
DROP SEQUENCE IF EXISTS public.sessions_id_session_seq;
DROP TABLE IF EXISTS public.sessions;
DROP TABLE IF EXISTS public.prueba;
DROP SEQUENCE IF EXISTS public.levels_id_level_seq;
DROP TABLE IF EXISTS public.levels;
DROP SEQUENCE IF EXISTS public.level_results_id_result_seq;
DROP TABLE IF EXISTS public.level_results;
DROP TABLE IF EXISTS public.admins;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    id_admin integer NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(120) NOT NULL,
    phone character varying(20) NOT NULL,
    username character varying(60) NOT NULL,
    password_hash character varying(255) NOT NULL,
    registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: admins_id_admin_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admins ALTER COLUMN id_admin ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_admin_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: level_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.level_results (
    id_result integer NOT NULL,
    id_session integer NOT NULL,
    id_level integer NOT NULL,
    finishing_time integer,
    attempts integer,
    fails integer,
    completed boolean
);


--
-- Name: level_results_id_result_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.level_results_id_result_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: level_results_id_result_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.level_results_id_result_seq OWNED BY public.level_results.id_result;


--
-- Name: levels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.levels (
    id_level integer NOT NULL,
    name character varying(100),
    difficulty integer
);


--
-- Name: levels_id_level_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.levels_id_level_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: levels_id_level_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.levels_id_level_seq OWNED BY public.levels.id_level;


--
-- Name: prueba; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prueba (
    id integer
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id_session integer NOT NULL,
    id_student integer NOT NULL,
    beginning_date timestamp without time zone,
    end_date timestamp without time zone,
    device character varying(50)
);


--
-- Name: sessions_id_session_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sessions_id_session_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sessions_id_session_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sessions_id_session_seq OWNED BY public.sessions.id_session;


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id_student integer NOT NULL,
    id_tutor integer,
    age integer NOT NULL,
    gender character(1) CONSTRAINT students_genre_not_null NOT NULL,
    country character(2),
    neurodivergency character varying(50),
    registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    email character varying(120),
    password_hash character varying(255),
    name character varying(120),
    CONSTRAINT students_gender_check CHECK ((gender = ANY (ARRAY['M'::bpchar, 'F'::bpchar, 'O'::bpchar])))
);


--
-- Name: students_id_student_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.students_id_student_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: students_id_student_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.students_id_student_seq OWNED BY public.students.id_student;


--
-- Name: tutors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutors (
    id_tutor integer NOT NULL,
    email character varying(120) NOT NULL,
    password_hash character varying(255) NOT NULL,
    country character(2),
    registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    name character varying(120),
    gender character(1),
    age integer,
    degree character varying(20),
    CONSTRAINT tutors_degree_check CHECK (((degree)::text = ANY (ARRAY['licenciatura'::text, 'maestria'::text, 'doctorado'::text, 'postdoctorado'::text, 'padre-madre'::text]))),
    CONSTRAINT tutors_gender_check CHECK ((gender = ANY (ARRAY['M'::bpchar, 'F'::bpchar, 'O'::bpchar])))
);


--
-- Name: tutors_id_tutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tutors_id_tutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tutors_id_tutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tutors_id_tutor_seq OWNED BY public.tutors.id_tutor;


--
-- Name: level_results id_result; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_results ALTER COLUMN id_result SET DEFAULT nextval('public.level_results_id_result_seq'::regclass);


--
-- Name: levels id_level; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.levels ALTER COLUMN id_level SET DEFAULT nextval('public.levels_id_level_seq'::regclass);


--
-- Name: sessions id_session; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions ALTER COLUMN id_session SET DEFAULT nextval('public.sessions_id_session_seq'::regclass);


--
-- Name: students id_student; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students ALTER COLUMN id_student SET DEFAULT nextval('public.students_id_student_seq'::regclass);


--
-- Name: tutors id_tutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutors ALTER COLUMN id_tutor SET DEFAULT nextval('public.tutors_id_tutor_seq'::regclass);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.admins (id_admin, name, email, phone, username, password_hash, registration_date) FROM stdin;
1	Admin Principal	admin.principal@mail.com	+525512345678	admin.principal	$2a$11$Ivtp3EQfSA3jHjGy/3kP4.MeL4dYIqCSCC0ErRvh8ZnAXqs3yDAWW	2026-05-13 04:26:04.220416
2	Temp Admin	temp.admin@mail.com	+525500000001	temp.admin	$2a$11$g9y0wHPg4wotpshcLuRybOO2vnRl4Slh7Bfs.8UVJDRAo7HHiF9xy	2026-05-20 07:15:04.325885
\.


--
-- Data for Name: level_results; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.level_results (id_result, id_session, id_level, finishing_time, attempts, fails, completed) FROM stdin;
1	1	1	1800	1	0	t
2	1	2	2400	2	1	t
3	2	1	1500	1	0	t
4	2	3	3600	3	2	f
5	3	2	2100	2	1	t
6	3	4	4200	4	3	t
7	4	1	1200	1	0	t
8	4	3	3300	3	1	t
9	5	2	2700	2	1	t
10	5	5	5400	5	4	f
11	6	3	3000	3	2	t
12	6	4	4500	4	2	f
13	7	1	1600	1	0	t
14	7	2	2300	2	1	t
15	8	4	4000	4	3	t
16	8	5	5100	5	3	t
17	9	2	2200	2	1	t
18	9	3	3500	3	2	t
19	10	3	3400	3	2	t
20	10	5	5500	5	4	f
21	11	1	1500	1	0	t
22	11	2	2400	2	1	t
23	12	1	900	1	0	t
24	13	2	1200	2	1	t
25	13	3	1800	3	1	t
26	14	1	1500	1	0	t
27	14	4	2400	4	2	t
28	15	3	1800	3	1	t
29	15	5	2700	5	3	f
30	12	2	1500	2	1	t
31	16	1	5432	1	0	t
32	17	1	10267	1	0	t
33	17	2	5309	1	0	t
34	17	3	4067	1	0	t
35	18	1	17871	1	0	t
36	18	2	9712	1	0	t
37	18	1	11399	1	0	t
38	19	1	10580	1	0	t
39	19	2	5380	1	0	t
40	19	3	9466	1	0	t
41	20	1	8186	1	0	t
42	20	2	31065	1	0	t
43	20	3	6789	1	0	t
44	21	4	28621	1	0	t
45	21	1	39061	1	0	t
46	21	2	9307	1	0	t
47	22	1	8010	1	0	t
48	22	2	10326	1	0	t
49	23	2	92685	1	0	t
50	24	1	87013	1	0	t
51	25	1	19457	1	0	t
52	25	2	14912	1	0	t
53	25	3	35144	1	0	t
54	25	4	10902	1	0	t
55	26	1	78209	1	0	t
56	26	1	30375	1	0	t
57	26	2	5881	1	0	t
58	26	3	17366	1	0	t
59	27	1	10839	1	0	t
60	27	2	6881	1	0	t
61	27	3	7767	1	0	t
62	28	1	119821	1	0	t
64	29	1	36903	1	0	t
65	30	1	56831	1	0	t
76	42	1	15582	1	0	t
77	43	1	65479	1	0	t
80	46	1	18831	1	0	t
81	46	6	5927	1	0	t
82	47	1	17199	1	0	t
83	47	2	9113	1	0	t
84	48	1	9496	1	0	t
85	49	5	54262	1	0	t
\.


--
-- Data for Name: levels; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.levels (id_level, name, difficulty) FROM stdin;
1	Beginner	1
2	Elementary	2
3	Intermediate	5
4	Advanced	8
5	Expert	10
6	Master	12
\.


--
-- Data for Name: prueba; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.prueba (id) FROM stdin;
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sessions (id_session, id_student, beginning_date, end_date, device) FROM stdin;
1	17	2026-05-01 10:00:00	2026-05-01 11:30:00	Laptop
2	18	2026-05-02 14:00:00	2026-05-02 15:45:00	Tablet
3	19	2026-05-03 09:00:00	2026-05-03 10:15:00	Phone
4	20	2026-05-04 16:00:00	2026-05-04 17:30:00	Laptop
5	21	2026-05-05 11:00:00	2026-05-05 12:45:00	Desktop
6	22	2026-05-06 13:00:00	2026-05-06 14:30:00	Tablet
7	23	2026-05-07 10:30:00	2026-05-07 11:45:00	Phone
8	24	2026-05-08 15:00:00	2026-05-08 16:45:00	Laptop
9	25	2026-05-09 09:30:00	2026-05-09 10:45:00	Desktop
10	26	2026-05-09 14:00:00	2026-05-09 15:30:00	Tablet
11	20	2026-05-10 00:34:03	2026-05-10 01:39:03	TutorFilterToday
12	20	2026-05-07 10:15:00	2026-05-07 10:55:00	TutorFilter3d
13	20	2026-04-30 16:20:00	2026-04-30 17:10:00	TutorFilter10d
14	20	2026-04-20 12:40:00	2026-04-20 13:45:00	TutorFilter20d
15	20	2026-03-21 09:10:00	2026-03-21 10:25:00	TutorFilter50d
16	17	2026-05-25 19:11:05.355159	2026-05-25 19:11:11.686193	web
17	17	2026-05-25 19:12:14.276368	2026-05-25 19:12:38.895254	web
18	17	2026-05-25 19:15:46.067746	2026-05-25 19:17:45.131025	web
19	17	2026-05-25 19:18:12.43437	2026-05-25 19:19:34.733389	web
20	17	2026-05-25 19:20:29.531973	2026-05-25 19:21:20.874932	web
21	17	2026-05-25 19:21:50.129668	2026-05-25 19:23:25.420181	web
22	17	2026-05-25 19:24:46.942278	2026-05-25 19:25:09.370871	web
23	17	2026-05-25 19:26:30.907336	2026-05-25 19:28:03.796575	web
24	17	2026-05-25 19:31:21.7224	2026-05-25 19:32:48.989965	web
25	17	2026-05-25 19:34:47.206821	2026-05-25 19:36:15.593292	web
26	17	2026-05-25 20:33:28.350974	2026-05-25 21:06:37.01823	web
27	31	2026-05-25 21:15:24.869347	2026-05-25 21:15:54.563567	web
28	17	2026-05-25 21:43:37.405747	2026-05-25 21:45:37.286723	web
29	17	2026-05-27 00:51:23.95544	2026-05-27 00:53:11.861512	web
30	17	2026-05-27 01:01:09.860456	2026-05-27 01:02:06.770325	web
42	19	2026-06-05 16:55:04.686016	2026-06-05 16:55:20.713847	web
43	17	2026-06-05 17:18:49.78067	2026-06-05 17:19:55.340867	web
46	17	2026-06-05 19:06:07.124979	2026-06-05 19:06:36.872224	web
47	17	2026-06-05 19:33:04.37649	2026-06-05 19:33:33.142036	web
48	70	2026-06-05 19:37:09.988165	2026-06-05 19:37:19.563844	web
49	75	2026-06-06 00:48:38.945152	2026-06-06 00:49:33.725981	web
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.students (id_student, id_tutor, age, gender, country, neurodivergency, registration_date, email, password_hash, name) FROM stdin;
17	47	15	M	MX	ADHD	2026-05-11 22:37:59.117325	luis.martinez@mail.com	$2a$11$Gx6yrG8ixQPigyB6LGu21Oih9zEngJVv2kH/OHXAok8JZd.8rhx5G	Luis Martínez
18	47	16	F	MX	Dyslexia	2026-05-11 22:37:59.117325	sofia.garcia@mail.com	$2a$11$ggNJnKCiA6DIAJd/6Dmiy.7akVI8/gXlqHqWKpkICozG0T0TXEM86	Sofia García
19	48	14	M	ES	\N	2026-05-11 22:37:59.117325	pablo.rodriguez@mail.com	$2a$11$5AyoFtXW77mIDuvsLS0OWOq96CvSZr1uNPYL1/qGsBKz2MpPIq.V6	Pablo Rodríguez
20	48	17	F	ES	Autism Spectrum	2026-05-11 22:37:59.117325	carmen.lopez@mail.com	$2a$11$ZRE4YVeLZXvyUHUBUNHgqebbOB19acVDMnfasvrkv4Qiz.c1PN.yu	Carmen López
21	49	15	M	CO	ADHD	2026-05-11 22:37:59.117325	diego.sanchez@mail.com	$2a$11$XyYGO6XWYi2mIn4UN9MVM.Ao/Yill9llqEzZS18t.UZ80q7gEVeKa	Diego Sánchez
22	49	16	F	CO	\N	2026-05-11 22:37:59.117325	laura.gomez@mail.com	$2a$11$kZRwiJg2XR69M75i9LsluOvyt21NymBZKBWtxNocUvEN3cXaku/Wy	Laura Gómez
23	50	14	M	AR	\N	2026-05-11 22:37:59.117325	fernando.diaz@mail.com	$2a$11$/MRIVzIJ1f0bs/ktkTFHjO6/NVmiNGx3Tpt5Qz5yh.8Lw/88ioed.	Fernando Díaz
24	50	18	F	AR	Dyslexia	2026-05-11 22:37:59.117325	valentina.fernandez@mail.com	$2a$11$WSUhhhTBocbjqKuosO/IA.ooKICS7Ixb462Nu2JkJ54DGFWTaI7X6	Valentina Fernández
25	51	15	M	PE	\N	2026-05-11 22:37:59.117325	alejandro.torres@mail.com	$2a$11$iAhzi99WIDpeLEq6emRgU.0GzN49nncQMyfF5OD2sZL81s8iMG3Du	Alejandro Torres
26	51	17	F	PE	ADHD Dyslexia	2026-05-11 22:37:59.117325	martina.cruz@mail.com	$2a$11$ci1uX6bVM4nDtteshfWnouTJh1kRkqo.Y6wSu.GgtYuLFJFrEApdO	Martina Cruz
42	\N	14	F	MX	ninguna	2026-05-27 02:12:09.48918	newman.student.17798479278229761@mail.com	$2a$11$IAayX7Y/jRHC3HQ2NTNjtuoiMrsVesYC/1I/Q4h3gEEWAiFL2clmS	Newman Student
27	52	15	F	MX	ADHD	2026-05-21 06:34:45.682047	student.auto.1779345284390@mail.com	$2a$11$T0eLIEYFb5fqJ03RJvQ5QuwUcbr.b.RW6NELobVq85vexVnv05Ffa	Student Auto Edit 1779345284390
43	\N	13	F	MX	ninguna	2026-05-27 02:12:14.688036	newman.logs.17798479337005599@mail.com	$2a$11$Cl92qOxFc5RbCAsXX14Qfex55u2oFYlGaabV8QTVxdtSghbgnfRfC	Newman Logs Student
28	53	15	F	MX	None	2026-05-21 08:07:41.619981	student.e2e.1779350832@mail.com	$2a$11$C/d.VkyiT7ymdYKWq4URDevc/uzPX9BVytLW8C/QtoiukRX3d/9L.	Student E2E Updated
29	54	14	F	MX	None	2026-05-21 08:09:32.301308	student.gw.1779350971@mail.com	$2a$11$y2se1WQCQDpg5GJFTRMHjO9sPqltXocHARunSU4282MIvNTvhu1Gy	Student GW Updated
55	\N	13	F	MX	ninguna	2026-05-27 04:52:02.969227	newman.logs.1779857522145746@mail.com	$2a$11$GjxHRsGB0ZYb3Rn4jR/yNe51OC.3eZUGJfLPqYKby/2/YMdvuhiOS	Newman Logs Student
30	55	14	F	MX	None	2026-05-21 08:10:00.776407	student.gw.1779350999@mail.com	$2a$11$DfMhx/jTIHVjvYUQOZzWHuNfQzyBz6ic7skMk7SiKWSlJ3Qp8AScO	Student GW Updated
31	47	5	M	MX	tda	2026-05-25 21:13:23.680257	chuchito@gmail.com	$2a$11$ZxFKiBylD1h1oT4vSie8pu2t9/7MqIwf9z3mhwlCdNE6kn9EiFPcy	seto marquez
32	\N	14	F	MX	ninguna	2026-05-27 01:23:08.892614	newman.student.30db1bf1@mail.com	$2a$11$2VnFJLdNjXqZwV1XcVCV0OjzdtxSxNQTXEKXASIpL04LJySMAeYOy	Newman Student
33	\N	14	F	MX	ninguna	2026-05-27 01:26:16.499672	newman.student.17798451747242928@mail.com	$2a$11$/83P3wh9yp5/TraeZqDWG.r2xfpVaHl2qTlbnVp8rYT/4lYdZrgDi	Newman Student
34	\N	13	F	MX	ninguna	2026-05-27 01:32:12.410024	newman.logs.17798455316121360@mail.com	$2a$11$wW8CFIhFcgpBFLcmqc.2jutjPedi9/L7O6fL3.rk4ayIJ/LAEGEv6	Newman Logs Student
35	\N	13	F	MX	ninguna	2026-05-27 01:32:57.425907	newman.logs.17798455764759230@mail.com	$2a$11$NbgnohSZePEef6.DiZgWEObyNjZAsHQ4NAI65Fy/hmo/eZf2fXJSK	Newman Logs Student
45	\N	14	F	MX	ninguna	2026-05-27 04:48:18.520958	newman.student.17798572963739713@mail.com	$2a$11$2.tfc8votiUBLB8uldNXGOE7rylaVUtbrNWdKk6/rL1idXnNPalie	Newman Student
46	\N	13	F	MX	ninguna	2026-05-27 04:48:46.917832	newman.logs.17798573258356157@mail.com	$2a$11$ugrZN1rPOo/Cu3Kpe9lJHOVp7cQ1SDbxjSCu6flrUXK1WrQFS5iNi	Newman Logs Student
66	\N	14	F	MX	ninguna	2026-06-05 17:26:28.381108	newman.student.17806803867865274@mail.com	$2a$11$CC5xFSC5Rs8OjoAprAxO3eU.ARXSeFmDh0Fd4cqgKL4uG53WMF46e	Newman Student
48	\N	14	F	MX	ninguna	2026-05-27 04:50:23.712495	newman.student.17798574215529542@mail.com	$2a$11$sVcvwnTMGanFJ97ibApnYeqnn9A5nQsa7jBVFk/vC0t1lU/auT8ie	Newman Student
49	\N	13	F	MX	ninguna	2026-05-27 04:50:30.511204	newman.logs.17798574296313902@mail.com	$2a$11$icX3hnsDVPt2VOeTB1mCa.sQxbwDgXN3znun6whO6E/O4XrKrsaR6	Newman Logs Student
41	\N	14	F	MX	ninguna	2026-05-27 02:11:48.964425	newman.student.17798479073248519@mail.com	$2a$11$dSRmSLEha3IU1Kb.BB.F1.0kHwpotJwMtMJhXiRG7eeoJObNmjNdy	Newman Student
57	\N	14	F	MX	ninguna	2026-05-27 04:56:10.433792	newman.student.17798577682307505@mail.com	$2a$11$Ifw0qyei0JWHdTagVNMBVe1q7zU.4R/etLf0lz50JhvMFyq0WyNYK	Newman Student
58	\N	13	F	MX	ninguna	2026-05-27 04:56:19.25722	newman.logs.1779857778105827@mail.com	$2a$11$kvyKDOiqrCGycZ5K/XYqNOXA28.ETZ.ut20UyyHzUBDxvEpl04CyG	Newman Logs Student
51	\N	13	F	MX	ninguna	2026-05-27 04:51:34.402615	newman.logs.17798574935294863@mail.com	$2a$11$dsge8ejjjyjorHUzSxkU2.jRolE7sIu6GfWhf.gODBILk9f0P7wly	Newman Logs Student
52	\N	14	F	MX	ninguna	2026-05-27 04:51:35.616517	newman.student.17798574935532229@mail.com	$2a$11$inHCZyhNejRKzlsQPn8O7uNdmnfc3kXO0.BTTt1l8WYXGvsd6MOcK	Newman Student
63	\N	14	F	MX	ninguna	2026-06-05 17:24:11.632561	newman.student.17806802496488167@mail.com	$2a$11$/xUphI5.4JtnLWatPqgmce3MzJsPAgD7yapUoAwfPCEmfwfPnu5eu	Newman Student
54	\N	14	F	MX	ninguna	2026-05-27 04:51:57.64825	newman.student.17798575159182999@mail.com	$2a$11$zbi3AyClRAtHB/tFCTkE0.QW77bUBMeQE188EH7bRbkYgG5ZaMHZm	Newman Student
64	\N	13	F	MX	ninguna	2026-06-05 17:24:16.159297	newman.logs.17806802552271486@mail.com	$2a$11$p.CACGuFvP5z5ZBRVT5TAuc0aPWdc4kNh6cK5D1B8EtY9bd4Rmrpi	Newman Logs Student
60	\N	14	F	MX	ninguna	2026-05-27 05:13:28.157578	newman.student.17798588064029616@mail.com	$2a$11$SfNsdD8w2I10BSF6d7TFIeuXeq0h1s9X45RPYH1vHA2Q8IAA2teKC	Newman Student
61	\N	13	F	MX	ninguna	2026-05-27 05:13:32.550826	newman.logs.17798588117245412@mail.com	$2a$11$.s9g.J3CqiJCAv9oWG2ErOKthxP9HG7V68Bnp2CTREaWLwG2izJEy	Newman Logs Student
69	\N	5	M	MX	tda	2026-06-05 19:36:08.100209	leomarquez@gmail.com	$2a$11$UWCFS2mK/F4nA.cSuiIfke/EypY9ZpS2iqRxiur84H1aJy91ZZh9W	leo marquez
67	\N	13	F	MX	ninguna	2026-06-05 17:26:33.233748	newman.logs.17806803923045874@mail.com	$2a$11$lYBWTDQITktuJ8YaQ5SY5OcXaVsNpWKbZNKYzWZVxGH06NIPkIH2S	Newman Logs Student
70	47	5	M	MX	autismo	2026-06-05 19:36:53.908883	correo@gmail.com	$2a$11$sh8aZp9mOuOMcaOkDRVv3OEWxQzl.dGQGwhnY1acb84cgnKjxjPVi	leoo marquez
71	\N	5	M	MX	tda	2026-06-05 19:59:54.545304	asd@gmail.com	$2a$11$56cxI.lRUmVKIWe/kBJsd.54GtrCv.e7xbmAZINVwGD6LP6ncr7GC	asdasdas
72	47	5	M	MX	autismo	2026-06-05 20:01:10.721907	asdd@gmail.com	$2a$11$72miQnqBGxYrrEGMWgP0Aucu0KcU4e7BsTWZvyCm7ayn8LALbneKG	seto marquezs
73	82	5	M	MX	autismo	2026-06-05 20:21:28.336787	patito@gmail.com	$2a$11$3sxvKpzS46pbfRaq1YCWturP0sze6APmzfHjjgkPXtla8EFOG00qC	leo marquez
74	\N	15	F	MX	\N	2026-06-06 00:47:12.46771	correoo@gmail.com	$2a$11$mRSUX6inTot5g422AzQtc.YcpSQHBForQqF/9vNN5vEYyJ9d3RLm6	juan perez
75	47	5	M	MX	\N	2026-06-06 00:48:06.537555	perro@gmail.com	$2a$11$14YLPp8Xe5K0bBZfM/NmeuuR2R9J8Qk3dB9jA8XHKEqx8zp.26Ula	carlos ramirez
\.


--
-- Data for Name: tutors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tutors (id_tutor, email, password_hash, country, registration_date, name, gender, age, degree) FROM stdin;
48	maria.lopez@mail.com	$2a$11$i2eX1GOzYfSOOFy9Bp.5l.6w9BViixG/CCwiK80SLJr4xopEfRCga	MX	2026-05-11 22:37:46.526971	María López	F	32	doctorado
49	carlos.rodriguez@mail.com	$2a$11$qOqcgPrUeY6LlLJ/TPNvouXb02gB7xPMagjoYqEFFRvQYzqWwqOY.	CO	2026-05-11 22:37:46.526971	Carlos Rodríguez	M	40	maestria
50	ana.martinez@mail.com	$2a$11$RwnJs9JOu1hIH8e3Uo3mx.4q10A/ahTgvjTbht2rf..gcHpZxCcWa	AR	2026-05-11 22:37:46.526971	Ana Martínez	F	28	licenciatura
51	pedro.sanchez@mail.com	$2a$11$aSGUkdASMCThqijut58T4uYOdW8fE6Yppr5/pl6DKBgkm69J7RznO	PE	2026-05-11 22:37:46.526971	Pedro Sánchez	M	38	postdoctorado
52	tutor.auto.1779345284390@mail.com	$2a$11$c5ENUxRfQkwBvF5/WbXKJOzNXu8SdZV/V0l23BsJrG3N78BIlWGJm	MX	2026-05-21 06:34:44.940774	Tutor Auto ServiceCheck 1779345537085	M	37	doctorado
53	tutor.e2e.1779350832@mail.com	$2a$11$h1yE9pFbN2dpw1LXGhdHBODRUc6b0/hqQYvtXVeG8gU2hjNjEEPLG	MX	2026-05-21 08:07:35.671265	Tutor E2E Updated	M	40	doctorado
54	tutor.gw.1779350971@mail.com	$2a$11$Ga98TRyXFtZlMYLRyowppe8EpdZ59njyJ9z/VWMSA7ayXV7idhtTq	MX	2026-05-21 08:09:31.95006	Tutor GW Updated	M	39	doctorado
55	tutor.gw.1779350999@mail.com	$2a$11$eqM3BWPUc8FcUsyyt3lUv.QKP2iIYWtVpJb6Rasy9SNAKUXvyzytW	MX	2026-05-21 08:10:00.450451	Tutor GW Updated	M	39	doctorado
74	newman.tutor.17798577682307505@mail.com	$2a$11$b7nAmmKERQP4t4oWOQ374.dtsw.m2KiJtaQPGGV9LZia0OYjwkRm2	MX	2026-05-27 04:56:11.124767	Newman Tutor	M	39	maestria
56	newman.tutor.17798451747242928@mail.com	$2a$11$Uzdd/Mqsd7wYvBHUpMtCNu8PgsQQd36DMlNTwu.YlwERvjU8qLddm	MX	2026-05-27 01:26:16.946237	Newman Tutor	M	39	maestria
58	tmp.tutor.login.1779846346315@mail.com	TutorPass123!	MX	2026-05-27 01:45:46.321018	Tmp Tutor Login	M	34	maestria
76	newman.tutor.17798588064029616@mail.com	$2a$11$cnbLNbK2YneoA.9Rd2/TbO.c4aVRnjPt7AQaF0tQ6nIg9awPsESe2	MX	2026-05-27 05:13:28.644848	Newman Tutor	M	39	maestria
63	newman.tutor.17798479073248519@mail.com	$2a$11$AQoK9cfw9FBbVT0UCgVm..XOBH5Z6buIVkgDBATCh3zZfNCBuohLG	MX	2026-05-27 02:11:49.424381	Newman Tutor	M	39	maestria
64	newman.tutor.17798479278229761@mail.com	$2a$11$u6nFZB8DY2JzPJj9rYPkDuV.TEQToVFRxGyadB.zoU8ZDJ7TmiJzm	MX	2026-05-27 02:12:09.92526	Newman Tutor	M	39	maestria
66	newman.tutor.17798572963739713@mail.com	$2a$11$HzyjpsdNnHZLRP.XUlube.5dVdHhuYLgapNWHiFj/550jldYawo6m	MX	2026-05-27 04:48:19.078771	Newman Tutor	M	39	maestria
78	newman.tutor.17806802496488167@mail.com	$2a$11$gdD5C80v8WLNYfS52b6oUuwh/JLEbA.LhSoMXc7Vjdu9r.c9Se8Fe	MX	2026-06-05 17:24:12.131888	Newman Tutor	M	39	maestria
68	newman.tutor.17798574215529542@mail.com	$2a$11$TbG5pXGB.L1ijDpcg8MqoeGqxqM8qdgGrPvnHzI2WYmIBbc3Rn8Gu	MX	2026-05-27 04:50:24.46662	Newman Tutor	M	39	maestria
70	newman.tutor.17798574935532229@mail.com	$2a$11$QtHn0Bxn5SgRQULiKQm90.L5r6/1SNmM4FiQsMN4sWzCgIGDefmdO	MX	2026-05-27 04:51:36.225193	Newman Tutor	M	39	maestria
72	newman.tutor.17798575159182999@mail.com	$2a$11$YyOd.csviTj5rxOcnmd7heZtGXcp.PwRP03Ail0sSgBD3hNRcNroW	MX	2026-05-27 04:51:58.184734	Newman Tutor	M	39	maestria
80	newman.tutor.17806803867865274@mail.com	$2a$11$dNnq3fSTQgnQ.ZQY4S87QOEwP4iRtkFxMopDeVPJBISWPPcrNxyOi	MX	2026-06-05 17:26:28.913458	Newman Tutor	M	39	maestria
82	dguezs@m.com	$2a$11$gk0fmu54IQvtJ..hlqxBaOUObhIEe3OMvW71dudNCZpXBKwO8MZ4O	MX	2026-06-05 19:57:23.36374	Saul Dominguez	M	42	padre-madre
47	juan.garcia@mail.com	$2a$11$LJNg4QiK9v4ZaC/vrzVQz.GMdoz.phnzVlu3ky1SlWKDbdkzZfy/.	MX	2026-05-11 22:37:46.526971	Juan García	M	49	maestria
\.


--
-- Name: admins_id_admin_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.admins_id_admin_seq', 13, true);


--
-- Name: level_results_id_result_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.level_results_id_result_seq', 85, true);


--
-- Name: levels_id_level_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.levels_id_level_seq', 19, true);


--
-- Name: sessions_id_session_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sessions_id_session_seq', 49, true);


--
-- Name: students_id_student_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.students_id_student_seq', 75, true);


--
-- Name: tutors_id_tutor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tutors_id_tutor_seq', 82, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id_admin);


--
-- Name: level_results level_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_results
    ADD CONSTRAINT level_results_pkey PRIMARY KEY (id_result);


--
-- Name: levels levels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.levels
    ADD CONSTRAINT levels_pkey PRIMARY KEY (id_level);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id_session);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id_student);


--
-- Name: tutors tutors_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutors
    ADD CONSTRAINT tutors_email_key UNIQUE (email);


--
-- Name: tutors tutors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutors
    ADD CONSTRAINT tutors_pkey PRIMARY KEY (id_tutor);


--
-- Name: admins_email_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX admins_email_key ON public.admins USING btree (email);


--
-- Name: admins_username_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX admins_username_key ON public.admins USING btree (username);


--
-- Name: level_results level_results_id_level_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_results
    ADD CONSTRAINT level_results_id_level_fkey FOREIGN KEY (id_level) REFERENCES public.levels(id_level);


--
-- Name: level_results level_results_id_session_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level_results
    ADD CONSTRAINT level_results_id_session_fkey FOREIGN KEY (id_session) REFERENCES public.sessions(id_session);


--
-- Name: sessions sessions_id_student_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_id_student_fkey FOREIGN KEY (id_student) REFERENCES public.students(id_student);


--
-- Name: students students_id_tutor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_id_tutor_fkey FOREIGN KEY (id_tutor) REFERENCES public.tutors(id_tutor);


--
-- PostgreSQL database dump complete
--

\unrestrict EZ8A9GBZT6YqkMq5Hc9LCk88UVwcLZqEmAaaNTDv71o6l4iN787ebH0P8ZcSpgZ

