# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fingers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fingers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfingers.proto\x12\x07\x66ingers\"5\n\x0c\x46rameRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tclient_id\x18\x02 \x01(\t\"q\n\x0e\x46ingerResponse\x12\x11\n\tleft_hand\x18\x01 \x01(\x05\x12\x12\n\nright_hand\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x16\n\x0ehands_detected\x18\x04 \x01(\x08\x12\x11\n\tclient_id\x18\x05 \x01(\t2T\n\x0e\x46ingerDetector\x12\x42\n\x0cStreamFrames\x12\x15.fingers.FrameRequest\x1a\x17.fingers.FingerResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fingers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=26
  _globals['_FRAMEREQUEST']._serialized_end=79
  _globals['_FINGERRESPONSE']._serialized_start=81
  _globals['_FINGERRESPONSE']._serialized_end=194
  _globals['_FINGERDETECTOR']._serialized_start=196
  _globals['_FINGERDETECTOR']._serialized_end=280
# @@protoc_insertion_point(module_scope)
